curl --request GET \
	--url 'https://netflix54.p.rapidapi.com/search/?query=stranger&offset=0&limit_titles=50&limit_suggestions=20&lang=en' \
	--header 'X-RapidAPI-Host: netflix54.p.rapidapi.com' \
	--header 'X-RapidAPI-Key: f201f5fcb2msh76a0281b39a06d3p101966jsnf914fe715368'