import './globals.css'
import { Inter } from 'next/font/google'
import Header from './components/Header'
const inter = Inter({ subsets: ['latin'] })
import { Roboto } from 'next/font/google'
import Footer from './components/Footer'
const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
})
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={roboto.className}>
      <body className={inter.className}>
        <Header/>
        {children}
       <Footer/>
        </body>
    </html>
  )
}
